name = "generator-nav-network"
main = "worker.js"
compatibility_date = "2026-01-13"
node_compat = false

# 启用 ESBuild 捆绑
[build]
command = "esbuild --bundle src/worker.js --outfile=dist/worker.js --format=esm --target=es2020"
watch_dir = "src"

# 绑定 KV 命名空间（替换为你的 KV ID）
[[kv_namespaces]]
binding = "TIME_KV"
id = "64e305e814164aac9b0a8a961f00bc85"